UniversityLibraryWeb/Models/BookModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MongoDB.Bson;

namespace UniversityLibraryWeb.Models
{
    public class BookModel
    {
        public ObjectId Id { get; set; }
        public string Title { get; set; }
        public string Publisher { get; set; }
        public string Description { get; set; }
        public string[] Authors { get; set; }
    }

}

UniversityLibraryWeb/Models/DemandModel.cs
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityLibraryWeb.Models
{
    public class DemandModel
    {
        public ObjectId Id { get; set; }
        public string bookid { get; set; }
        public string username { get; set; }
        public DateTime date { get; set; }
    }
}

UniversityLibraryWeb/Models/SearchBooksModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityLibraryWeb.Models
{
    public class SearchBooksModel
    {
    }
}

UniversityLibraryWeb/Models/UserModel.cs
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityLibraryWeb.Models
{
    public class UserModel
    {
        public ObjectId Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

UniversityLibraryWeb/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using UniversityLibraryWeb.Injections;
using UniversityLibraryWeb.Models;

namespace UniversityLibraryWeb.Controllers
{
    /// <summary>
    /// Service that exposes queries through HTTP over Books
    /// </summary>    
    public class BooksController : ApiController
    {
        //Interface to provide IoC and implementation of dependency injection
        private readonly IBook bookHandler;

        public BooksController(IBook bookHandlerInjection) {            
            bookHandler = bookHandlerInjection; //Injection of dependency
        }

        [HttpGet]
        public IHttpActionResult GetBook(string id)
        {
            BookModel book = bookHandler.GetBook(id);
            if (book != null)
            {
                return Ok(book);
            }
            return NotFound();
        }

        [HttpGet]
        public IEnumerable<BookModel> GetAllBooks()
        {            
            return bookHandler.GetBooks();
        }

        [HttpGet]
        public IEnumerable<BookModel> GetBooksFiltered(string title, string publisher, string author)
        {
            return bookHandler.GetBooks(title, publisher, author);
        }

        [HttpGet]
        public IEnumerable<BookModel> GetBooksByTitle(string filter)
        {
            return bookHandler.GetBooksByTitle(filter);
        }

        [HttpGet]
        public IEnumerable<BookModel> GetBooksByPublisher(string filter)
        {
            return bookHandler.GetBooksByPublisher(filter);
        }

        [HttpGet]
        public IEnumerable<BookModel> GetBooksByAuthor(string filter)
        {
            return bookHandler.GetBooksByAuthor(filter);
        }

        [HttpGet]
        public IEnumerable<BookModel> GetBooksByTitleAndPublisher(string filterA, string filterB)
        {
            return bookHandler.GetBooksByTitleAndPublisher(filterA, filterB);
        }

        [HttpGet]
        public IEnumerable<BookModel> GetBooksByTitleAndAuthor(string filterA, string filterB)
        {
            return bookHandler.GetBooksByTitleAndAuthor(filterA, filterB);
        }

        [HttpGet]
        public IEnumerable<BookModel> GetBooksByPublisherAndAuthor(string filterA, string filterB)
        {
            return bookHandler.GetBooksByPublisherAndAuthor(filterA, filterB);
        }
                
        [HttpPost]
        public IHttpActionResult Post(string id)
        {
            var demandPlaced = bookHandler.PlaceBookDemand(id);        
            return Ok();
        }        
    }
}

UniversityLibraryWeb/Controllers/BooksHistoricalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UniversityLibraryWeb.Controllers
{
    public class BooksHistoricalsController : Controller
    {
        // GET: BooksHistoricals
        public ViewResult Index()
        {
            ViewBag.Title = "University Library";
            return View("Historical");
        }
    }
}

UniversityLibraryWeb/Controllers/DemandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using UniversityLibraryWeb.Injections;
using UniversityLibraryWeb.Models;

namespace UniversityLibraryWeb.Controllers
{
    /// <summary>
    /// Service that exposes queries through HTTP over Book Demands
    /// </summary>   
    public class DemandsController : ApiController
    {
        //Interface to provide IoC and implementation of dependency injection
        private readonly IHistorical demandsHandler;

        public DemandsController(IHistorical demandsHandlerInjection)
        {
            demandsHandler = demandsHandlerInjection; //Injection of dependency
        }

        [HttpGet]
        public IEnumerable<DemandModel> GetAllDemands()
        {
            return demandsHandler.GetDemands();
        }

        [HttpPost]
        public IHttpActionResult Post(string id)
        {
            var demandCanceled = demandsHandler.CancelDemand(id);            
            return Ok();
        }
    }
}

UniversityLibraryWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UniversityLibraryWeb.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ViewResult Index()
        {
            ViewBag.Title = "University Library";
            return View();
        }
    }
}

UniversityLibraryWeb/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UniversityLibraryWeb.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ViewResult Index()
        {
            ViewBag.Title = "University Library";
            return View("Login");
        }
    }
}

UniversityLibraryWeb/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using UniversityLibraryWeb.Injections;
using UniversityLibraryWeb.Models;

namespace UniversityLibraryWeb.Controllers
{
    /// <summary>
    /// Service that exposes queries through HTTP to allow Members registration
    /// </summary>    
    public class RegisterController : ApiController
    {
        //Interface to provide IoC and implementation of dependency injection
        private readonly IRegister registerHandler;

        public RegisterController(IRegister registerHandlerInjection)
        {
            registerHandler = registerHandlerInjection; //Injection of dependency
        }

        [HttpPost]
        public IHttpActionResult Post(string dataA, string dataB)
        {
            var memberRegistered = registerHandler.RegisterMember(dataA, dataB);        
            return Ok();
        }        

        [HttpGet]
        public IHttpActionResult GetLoginMember(string dataA, string dataB)
        {
            UserModel user = registerHandler.LoginMember(dataA, dataB);
            if (user != null)
            {
                return Ok(user);
            }
            return NotFound();
        }
    }
}

UniversityLibraryWeb/Controllers/SearchBooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace UniversityLibraryWeb.Controllers
{
    public class SearchBooksController : Controller
    {       
        // GET: SearchBooks
        public ViewResult Index()
        {
            ViewBag.Title = "University Library";
            return View("SearchBooks");
        }        
    }
}

UniversityLibraryWeb/Views/BooksHistoricals/Historical.cshtml
@model UniversityLibraryWeb.Models.DemandModel

@{    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts
{
    <script>
        var demandsUrl = 'api/demands';       
        var defaultErrorMessage = 'An error has occurred and the search could not be completed, please try again.'

        $(document).ready(function () {
            $.getJSON(demandsUrl)
                    .done(function (data) {
                        $('#historicalList').empty();
                        if (data != null) {
                            $('<table class="table table-hover" id="demandsContainer">').appendTo($('#historicalList'));
                            $('#demandsContainer').append('<thead><tr><th>#</th><th>Book #</th><th>User Name</th><th>Date Placed</th><th>Cancel Demand</th></tr></thead>');
                            $.each(data, function (key, item) {
                                $('#demandsContainer').append('<tr><th>' + item.Id + '<input type="hidden" name="bookId_' + item.bookid + '" value="' + item.bookid + '"></th><td>' + item.bookid + '</td><td>'
                                    + item.username + '</td><td>'+ item.date + '</td><td><button type="button" class="btn btn-primary cancelDemandButton">Cancel Demand</button></td></tr>');
                            });                            
                            $('.cancelDemandButton').on("click", cancelDemand);
                        } else {
                            createInformationMessage(defaultErrorMessage);
                        }
                    })
                    .fail(function (jqXHR, textStatus, err) {
                        createInformationMessage(defaultErrorMessage);
                    });
        });

        function cancelDemand(event) {
            var bookId = $(event.target).parent().parent().find('input:hidden').val();            
            $.ajax({
                type: "POST",
                url: demandsUrl + "/" + bookId,
                dataType: "json"
            }).always(function (data) {
                $(event.target).parent().parent()[0].remove();
                $("#bookDemandPlacedModal").modal()
            });                        
        }

        function createInformationMessage(message) {
            $('<li>', { text: message }).appendTo($('#historicalList'));
        }
    </script>
}

<h2>Historical - Previous Book Demands <span class="glyphicon glyphicon-book" aria-hidden="true"></span></h2>
<br />
<div class="row">
    <br />
    <div class="col-md-12" id="historicalList">
    </div>
    <!-- Modal -->
    <div class="modal fade" id="bookDemandPlacedModal" tabindex="-1" role="dialog" aria-labelledby="bookDemandPlacedModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="bookDemandPlacedModalLabel">Book Demand Canceled</h4>
                </div>
                <div class="modal-body">
                    <div class="alert alert-success" role="alert"><strong>Thank you!</strong> Your request to cancel the book demand has been completed.</div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>


UniversityLibraryWeb/Views/Home/Index.cshtml

@{    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Welcome to the University Library application for members</h2>
<br />
<span>This application allows our registered members to search for Books, place demands on any available book and also check the historical of demands.</span>


UniversityLibraryWeb/Views/Login/Login.cshtml
@model UniversityLibraryWeb.Models.UserModel

@{    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts
{
    <script>
        var registrationUrl = 'api/register';        

        $(document).ready(function () {
            $('#registerButton').on("click", registerMember);
            $('#loginButton').on("click", login);
        });        

        function registerMember(event) {
            var username = $('#memberUsernameInput').val();
            var email = $('#memberPasswordInput').val();
            $.ajax({
                type: "POST",
                url: registrationUrl + "/" + username + "/" + email,
                dataType: "json"
            }).always(function (data) {                
                $("#infoModal").modal();
            });            
        }

        function login() {
            var username = $('#memberUsernameInput').val();
            var password = $('#memberPasswordInput').val();
            var loginUrl = registrationUrl + "/" + username + "/" + password;
            $.getJSON(loginUrl)
                    .done(function (usermodel) {                        
                        if (usermodel != null) {                            
                            $('input[name="hdnUser"]').val(username);
                            $('input[name="hdnPassword"]').val(password);
                            $('#memberUsernameInput').val('');
                            $('#memberPasswordInput').val('');
                            $("#loginModal").modal();
                        } else {
                            $("#loginFailedModal").modal();
                        }
                    })
                    .fail(function (jqXHR, textStatus, err) {
                        $("#loginFailedModal").modal();
                    });
        }        
    </script>
}

<h2>Login - Member Registration <span class="glyphicon glyphicon-user" aria-hidden="true"></span></h2>
<br />
<form>
    <div class="form-group">
        <label for="memberUsernameInput">User name</label>
        <input type="text" class="form-control" id="memberUsernameInput" placeholder="User name">
    </div>
    <div class="form-group">
        <label for="memberPasswordInput">Password</label>
        <input type="password" class="form-control" id="memberPasswordInput" placeholder="Password">
    </div>            
    <button type="button" class="btn btn-primary" id="loginButton">Login</button>
    <button type="button" class="btn btn-success" id="registerButton">Register <span class="glyphicon glyphicon-user" aria-hidden="true"></span></button>  
    <!-- Modal -->
    <div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="infoModalLabel">Member Registration</h4>
                </div>
                <div class="modal-body">
                    <div class="alert alert-success" role="alert"><strong>Thank you!</strong> Your registration has been completed.</div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>  
    <div class="modal fade" id="loginFailedModal" tabindex="-1" role="dialog" aria-labelledby="loginFailedModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="loginFailedModalLabel">Member Login</h4>
                </div>
                <div class="modal-body">
                    <div class="alert alert-danger" role="alert">You have not been logged to the application, please verify your User and Password.</div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>  
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="loginModalLabel">Member Login</h4>
                </div>
                <div class="modal-body">
                    <div class="alert alert-success" role="alert">You have been logged to the application.</div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>  
</form>

UniversityLibraryWeb/Views/SearchBooks/SearchBooks.cshtml
@model UniversityLibraryWeb.Models.SearchBooksModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts
{
    <script>
        var booksUrl = 'api/books';
        var booksFilteredUrl = 'api/books/getbooksfiltered';
        var booksByTitle = 'api/books/getbooksbytitle';
        var booksByPublisher = 'api/books/getbooksbypublisher';
        var booksByAuthor = 'api/books/getbooksbyauthor';
        var booksByTitleAndPublisher = 'api/books/getbooksbytitleandpublisher';
        var booksByTitleAndAuthor = 'api/books/getbooksbytitleandauthor';
        var booksByPublisherAndAuthor = 'api/books/getbooksbypublisherandauthor';
        var defaultErrorMessage = 'An error has occurred and the search could not be completed, please try again.'

        $(document).ready(function () {
            $('#search').click(function () {
                var title = $('#inputTitle').val();
                var publisher = $('#inputPublisher').val();
                var author = $('#inputAuthor').val();
                var list = $('#booksList');
                var queryUrl = booksUrl; //By default set to all books (No Filter)

                if (title != '' && publisher != '' && author != '') {
                    queryUrl = booksFilteredUrl + '/' + title + '/' + publisher + '/' + author; //All Filters
                } else if (title != '' && publisher != '' && author == '') {
                    queryUrl = booksByTitleAndPublisher + '/' + title + '/' + publisher; //Title and Publisher
                } else if (title != '' && publisher == '' && author != '') {
                    queryUrl = booksByTitleAndAuthor + '/' + title + '/' + author; //Title and Author
                } else if (title == '' && publisher != '' && author != '') {
                    queryUrl = booksByPublisherAndAuthor + '/' + publisher + '/' + author; // Publisher And Author
                } else if (title != '') {
                    queryUrl = booksByTitle + '/' + title; //Title
                } else if (publisher != '') {
                    queryUrl = booksByPublisher + '/' + publisher; // Publisher
                } else if (author != '') {
                    queryUrl = booksByAuthor + '/' + author; //Author
                }

                $.getJSON(queryUrl)
                    .done(function (data) {
                        list.empty();
                        if (data != null) {
                            $('<table class="table table-hover" id="booksContainer">').appendTo($('#booksList'));
                            $('#booksContainer').append('<thead><tr><th>#</th><th>Title</th><th>Publisher</th><th>Description</th><th>Authors</th><th>Place Demand</th></tr></thead>');
                            $.each(data, function (key, item) {
                                $('#booksContainer').append('<tr><th>' + item.Id + '<input type="hidden" name="bookId_' + item.Id + '" value="' + item.Id + '"></th><td>' + item.Title + '</td><td>' + item.Publisher
                                    + '</td><td data-toggle="tooltip" data-container="body" data-placement="right" title="' + item.Description + '">'
                                    + item.Description.substring(0, 100) + '...</td><td>' + item.Authors
                                    + '</td><td><button type="button" class="btn btn-info placeDemandButton">Place Demand</button></td></tr>');
                            });
                            $('[data-toggle="tooltip"]').tooltip();                            
                            $('.placeDemandButton').on("click", placeDemand);
                        } else {
                            createInformationMessage(defaultErrorMessage);
                        }
                    })
                    .fail(function (jqXHR, textStatus, err) {
                        createInformationMessage(defaultErrorMessage);
                    });
            });            
        });

        function placeDemand(event) {            
            var bookId = $(event.target).parent().parent().find('input:hidden').val();
            var user = $('input[name="hdnUser"]').val();            
            $.ajax({
                type: "POST",
                url: "api/books/" + bookId + "/" + user,
                dataType: "json"
            }).always(function (data) {
                $("#bookDemandPlacedModal").modal();
            });
        }

        function createInformationMessage(message) {
            $('<li>', { text: message }).appendTo($('#booksList'));
        }
    </script>
}

<h2>Search - Published Books <span class="glyphicon glyphicon-book" aria-hidden="true"></span></h2>
<br />
<div class="form-inline">
    <div class="row">
        <div class="col-md-11">
            <label for="inputTitle">Title:</label>
            <input type="text" class="form-control" id="inputTitle" placeholder="Mammal Species of the World">
            &nbsp;
            <label for="inputPublisher">Publisher:</label>
            <input type="text" class="form-control" id="inputPublisher" placeholder="JHU Press">
            &nbsp;
            <label for="inputAuthor">Author:</label>
            <input type="text" class="form-control" id="inputAuthor" placeholder="Don E. Wilson">
        </div>
        <div class="col-md-1">
            <button type="button" class="btn btn-primary" id="search">Search</button>
        </div>
    </div>
</div>
<div class="row">
    <br />
    <div class="col-md-12" id="booksList">
    </div>
    <!-- Modal -->
    <div class="modal fade" id="bookDemandPlacedModal" tabindex="-1" role="dialog" aria-labelledby="bookDemandPlacedModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="bookDemandPlacedModalLabel">Book Demand Placed</h4>
                </div>
                <div class="modal-body">
                    <div class="alert alert-success" role="alert"><strong>Thank you!</strong> Your request for a book demand has been placed.</div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>                    
                </div>
            </div>
        </div>
    </div>
</div>

UniversityLibraryWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("Scripts", false)    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>            
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Login - Member registration", "Index", "Login", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Search books", "Index", "SearchBooks", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Previous book demands", "Index", "BooksHistoricals", new { area = "" }, null)</li>                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <input type="hidden" name="hdnUser" value="">
        <input type="hidden" name="hdnPassword" value="">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - University Library members autoservice application</p>
        </footer>
    </div>    
</body>
</html>